# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nemo_Terminalus_v0.2.ui'serverзагрузка python кода на сервер
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


import sys
import glob
import serial
import time


def serial_ports():
    """ Lists serial port names

        :raises EnvironmentError:
            On unsupported or unknown platforms
        :returns:
            A list of the serial ports available on the system
    """
    if sys.platform.startswith('win'):
        ports = ['COM%s' % (i + 1) for i in range(256)]
    elif sys.platform.startswith('linux') or sys.platform.startswith('cygwin'):
        # this excludes your current terminal "/dev/tty"
        ports = glob.glob('/dev/tty[A-Za-z]*')
    elif sys.platform.startswith('darwin'):
        ports = glob.glob('/dev/tty.*')
    else:
        raise EnvironmentError('Unsupported platform')

    result = []
    for port in ports:
        try:
            s = serial.Serial(port)
            s.close()
            result.append(port)
        except (OSError, serial.SerialException):
            pass
    return result

ser = serial.Serial() # инициализация COM порта

class Ui_Nemo(object):

    ''' Инициализация портов при запуске программы '''
    def __init__(self):
        ''' начальные данные '''
        if serial_ports():
            self.data_serial_port = list(serial_ports())
        else:
            self.data_serial_port = ['None'] # первоначальные значения портов
        self.data_serial_port.append('Update')


    def setupUi(self, Nemo):
        Nemo.setObjectName("Nemo")
        Nemo.resize(648, 450)
        self.gridLayout = QtWidgets.QGridLayout(Nemo)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_ethernet = QtWidgets.QGroupBox(Nemo)
        self.groupBox_ethernet.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_ethernet.setFont(font)
        self.groupBox_ethernet.setStyleSheet("QGroupBox {\n"
"    font: bold;\n"
"    border: 2px solid silver;\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    padding: 0px 5px 0px 5px;\n"
"}")
        self.groupBox_ethernet.setObjectName("groupBox_ethernet")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_ethernet)
        self.gridLayout_7.setContentsMargins(10, 20, 10, 10)
        self.gridLayout_7.setSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_ip_host = QtWidgets.QLabel(self.groupBox_ethernet)
        self.label_ip_host.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_ip_host.setFont(font)
        self.label_ip_host.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ip_host.setLineWidth(1)
        self.label_ip_host.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ip_host.setIndent(0)
        self.label_ip_host.setObjectName("label_ip_host")
        self.gridLayout_7.addWidget(self.label_ip_host, 0, 0, 1, 1)
        self.pushButton_net_test = QtWidgets.QPushButton(self.groupBox_ethernet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_net_test.setFont(font)
        self.pushButton_net_test.setObjectName("pushButton_net_test")
        self.gridLayout_7.addWidget(self.pushButton_net_test, 2, 1, 1, 1)
        self.comboBox_net_ip = QtWidgets.QComboBox(self.groupBox_ethernet)
        self.comboBox_net_ip.setObjectName("comboBox_net_ip")
        self.comboBox_net_ip.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_net_ip, 0, 1, 1, 1)
        self.pushButton_net_connect = QtWidgets.QPushButton(self.groupBox_ethernet)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_net_connect.setFont(font)
        self.pushButton_net_connect.setStyleSheet("")
        self.pushButton_net_connect.setObjectName("pushButton_net_connect")
        self.gridLayout_7.addWidget(self.pushButton_net_connect, 2, 0, 1, 1)
        self.comboBox_net_port = QtWidgets.QComboBox(self.groupBox_ethernet)
        self.comboBox_net_port.setObjectName("comboBox_net_port")
        self.comboBox_net_port.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_net_port, 1, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(self.groupBox_ethernet)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_port.setFont(font)
        self.label_port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_port.setIndent(0)
        self.label_port.setObjectName("label_port")
        self.gridLayout_7.addWidget(self.label_port, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_ethernet, 2, 0, 1, 1)
        self.pushButton_start_end = QtWidgets.QPushButton(Nemo)
        self.pushButton_start_end.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_end.setFont(font)
        self.pushButton_start_end.setObjectName("pushButton_start_end")
        self.gridLayout.addWidget(self.pushButton_start_end, 3, 0, 1, 3)
        self.label_link = QtWidgets.QLabel(Nemo)
        self.label_link.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_link.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.label_link.setFont(font)
        self.label_link.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_link.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_link.setAlignment(QtCore.Qt.AlignCenter)
        self.label_link.setIndent(-1)
        self.label_link.setObjectName("label_link")
        self.gridLayout.addWidget(self.label_link, 4, 0, 1, 3)
        self.groupBox_uart = QtWidgets.QGroupBox(Nemo)
        self.groupBox_uart.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_uart.setFont(font)
        self.groupBox_uart.setStyleSheet("QGroupBox {\n"
"    font: bold;\n"
"    border: 2px solid silver;\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    padding: 0px 5px 0px 5px;\n"
"}")
        self.groupBox_uart.setObjectName("groupBox_uart")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_uart)
        self.gridLayout_6.setContentsMargins(10, 20, 10, 10)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_serial_port = QtWidgets.QLabel(self.groupBox_uart)
        self.label_serial_port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_serial_port.setFont(font)
        self.label_serial_port.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_serial_port.setLineWidth(1)
        self.label_serial_port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_serial_port.setIndent(0)
        self.label_serial_port.setObjectName("label_serial_port")
        self.gridLayout_6.addWidget(self.label_serial_port, 0, 0, 1, 1)
        self.comboBox_uart_data_bits = QtWidgets.QComboBox(self.groupBox_uart)
        self.comboBox_uart_data_bits.setObjectName("comboBox_uart_data_bits")
        self.comboBox_uart_data_bits.addItem("")
        self.comboBox_uart_data_bits.addItem("")
        self.comboBox_uart_data_bits.addItem("")
        self.comboBox_uart_data_bits.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_uart_data_bits, 2, 1, 1, 1)
        self.label_parity = QtWidgets.QLabel(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_parity.setFont(font)
        self.label_parity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_parity.setIndent(0)
        self.label_parity.setObjectName("label_parity")
        self.gridLayout_6.addWidget(self.label_parity, 3, 0, 1, 1)
        self.pushButton_uart_test = QtWidgets.QPushButton(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_uart_test.setFont(font)
        self.pushButton_uart_test.setObjectName("pushButton_uart_test")
        self.gridLayout_6.addWidget(self.pushButton_uart_test, 5, 1, 1, 1)
        self.label_data_bits = QtWidgets.QLabel(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_data_bits.setFont(font)
        self.label_data_bits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_data_bits.setIndent(0)
        self.label_data_bits.setObjectName("label_data_bits")
        self.gridLayout_6.addWidget(self.label_data_bits, 2, 0, 1, 1)
        self.comboBox_uart_parity = QtWidgets.QComboBox(self.groupBox_uart)
        self.comboBox_uart_parity.setObjectName("comboBox_uart_parity")
        self.comboBox_uart_parity.addItem("")
        self.comboBox_uart_parity.addItem("")
        self.comboBox_uart_parity.addItem("")
        self.comboBox_uart_parity.addItem("")
        self.comboBox_uart_parity.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_uart_parity, 3, 1, 1, 1)
        self.pushButton_uart_connect = QtWidgets.QPushButton(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_uart_connect.setFont(font)
        self.pushButton_uart_connect.setStyleSheet("")
        self.pushButton_uart_connect.setObjectName("pushButton_uart_connect")
        self.gridLayout_6.addWidget(self.pushButton_uart_connect, 5, 0, 1, 1)
        self.comboBox_uart_stop_bits = QtWidgets.QComboBox(self.groupBox_uart)
        self.comboBox_uart_stop_bits.setObjectName("comboBox_uart_stop_bits")
        self.comboBox_uart_stop_bits.addItem("")
        self.comboBox_uart_stop_bits.addItem("")
        self.comboBox_uart_stop_bits.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_uart_stop_bits, 4, 1, 1, 1)
        self.comboBox_uart_serial_port = QtWidgets.QComboBox(self.groupBox_uart)
        self.comboBox_uart_serial_port.setObjectName("comboBox_uart_serial_port")
        self.gridLayout_6.addWidget(self.comboBox_uart_serial_port, 0, 1, 1, 1)
        self.label_stop_bits = QtWidgets.QLabel(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_stop_bits.setFont(font)
        self.label_stop_bits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_stop_bits.setIndent(0)
        self.label_stop_bits.setObjectName("label_stop_bits")
        self.gridLayout_6.addWidget(self.label_stop_bits, 4, 0, 1, 1)
        self.comboBox_uart_baud_rate = QtWidgets.QComboBox(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_uart_baud_rate.setFont(font)
        self.comboBox_uart_baud_rate.setObjectName("comboBox_uart_baud_rate")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.comboBox_uart_baud_rate.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_uart_baud_rate, 1, 1, 1, 1)
        self.label_baud_rate = QtWidgets.QLabel(self.groupBox_uart)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_baud_rate.setFont(font)
        self.label_baud_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_baud_rate.setIndent(0)
        self.label_baud_rate.setObjectName("label_baud_rate")
        self.gridLayout_6.addWidget(self.label_baud_rate, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_uart, 0, 0, 2, 1)
        self.groupBox_command = QtWidgets.QGroupBox(Nemo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_command.setFont(font)
        self.groupBox_command.setStyleSheet("QGroupBox {\n"
"    font: bold;\n"
"    border: 2px solid silver;\n"
"    border-radius: 6px;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
" \n"
"    padding: 0px 5px 0px 5px;\n"
"}")
        self.groupBox_command.setObjectName("groupBox_command")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_command)
        self.gridLayout_8.setContentsMargins(5, 20, 5, 5)
        self.gridLayout_8.setSpacing(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_command)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        #self.listWidget.addItem(item) # убрать самую первую строку ''' мой код '''
        self.gridLayout_8.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_command, 0, 1, 3, 2)

        self.retranslateUi(Nemo)
        QtCore.QMetaObject.connectSlotsByName(Nemo)


        ''' МОЙ КОД '''

        # устанавливаем значения в выпадающем меню по умолчанию
        index_rate = self.comboBox_uart_baud_rate.findText("115200", QtCore.Qt.MatchFixedString)
        self.comboBox_uart_baud_rate.setCurrentIndex(index_rate)

        index_data_bits = self.comboBox_uart_data_bits.findText("8", QtCore.Qt.MatchFixedString)
        self.comboBox_uart_data_bits.setCurrentIndex(index_data_bits)

        index_parity = self.comboBox_uart_parity.findText("even", QtCore.Qt.MatchFixedString)
        self.comboBox_uart_parity.setCurrentIndex(index_parity)

        index_stop_bits = self.comboBox_uart_stop_bits.findText("2", QtCore.Qt.MatchFixedString)
        self.comboBox_uart_stop_bits.setCurrentIndex(index_stop_bits)


    def retranslateUi(self, Nemo):
        _translate = QtCore.QCoreApplication.translate
        Nemo.setWindowTitle(_translate("Nemo", "Nemo_Terminalus_v0.2"))
        self.groupBox_ethernet.setTitle(_translate("Nemo", "Ethernet"))
        self.label_ip_host.setText(_translate("Nemo", "IP / Host:"))
        self.pushButton_net_test.setText(_translate("Nemo", "Test"))
        self.comboBox_net_ip.setItemText(0, _translate("Nemo", "999.999.999.999"))
        self.pushButton_net_connect.setText(_translate("Nemo", "Connect"))
        self.comboBox_net_port.setItemText(0, _translate("Nemo", "9000"))
        self.label_port.setText(_translate("Nemo", "Port:"))
        self.pushButton_start_end.setText(_translate("Nemo", "Start"))
        self.label_link.setText(_translate("Nemo", "TextLabel"))
        self.groupBox_uart.setTitle(_translate("Nemo", "UART"))
        self.label_serial_port.setText(_translate("Nemo", "Serial Port:"))
        self.comboBox_uart_data_bits.setItemText(0, _translate("Nemo", "5"))
        self.comboBox_uart_data_bits.setItemText(1, _translate("Nemo", "6"))
        self.comboBox_uart_data_bits.setItemText(2, _translate("Nemo", "7"))
        self.comboBox_uart_data_bits.setItemText(3, _translate("Nemo", "8"))
        self.label_parity.setText(_translate("Nemo", "Parity:"))
        self.pushButton_uart_test.setText(_translate("Nemo", "Test"))
        self.label_data_bits.setText(_translate("Nemo", "Data Bits:"))
        self.comboBox_uart_parity.setItemText(0, _translate("Nemo", "none"))
        self.comboBox_uart_parity.setItemText(1, _translate("Nemo", "even"))
        self.comboBox_uart_parity.setItemText(2, _translate("Nemo", "odd"))
        self.comboBox_uart_parity.setItemText(3, _translate("Nemo", "mark"))
        self.comboBox_uart_parity.setItemText(4, _translate("Nemo", "space"))
        self.pushButton_uart_connect.setText(_translate("Nemo", "Connect"))
        self.comboBox_uart_stop_bits.setItemText(0, _translate("Nemo", "1"))
        self.comboBox_uart_stop_bits.setItemText(1, _translate("Nemo", "1.5"))
        self.comboBox_uart_stop_bits.setItemText(2, _translate("Nemo", "2"))
        self.label_stop_bits.setText(_translate("Nemo", "Stop Bits:"))
        self.comboBox_uart_baud_rate.setItemText(0, _translate("Nemo", "600"))
        self.comboBox_uart_baud_rate.setItemText(1, _translate("Nemo", "1200"))
        self.comboBox_uart_baud_rate.setItemText(2, _translate("Nemo", "2400"))
        self.comboBox_uart_baud_rate.setItemText(3, _translate("Nemo", "4800"))
        self.comboBox_uart_baud_rate.setItemText(4, _translate("Nemo", "9600"))
        self.comboBox_uart_baud_rate.setItemText(5, _translate("Nemo", "14400"))
        self.comboBox_uart_baud_rate.setItemText(6, _translate("Nemo", "19200"))
        self.comboBox_uart_baud_rate.setItemText(7, _translate("Nemo", "28800"))
        self.comboBox_uart_baud_rate.setItemText(8, _translate("Nemo", "38400"))
        self.comboBox_uart_baud_rate.setItemText(9, _translate("Nemo", "56000"))
        self.comboBox_uart_baud_rate.setItemText(10, _translate("Nemo", "57600"))
        self.comboBox_uart_baud_rate.setItemText(11, _translate("Nemo", "115200"))
        self.comboBox_uart_baud_rate.setItemText(12, _translate("Nemo", "128000"))
        self.comboBox_uart_baud_rate.setItemText(13, _translate("Nemo", "256000"))
        self.label_baud_rate.setText(_translate("Nemo", "Baud Rate:"))
        self.groupBox_command.setTitle(_translate("Nemo", "Command result"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        #item.setText(_translate("Nemo", ""))# "command - Ok"))
        self.listWidget.setSortingEnabled(__sortingEnabled)




    # мой код
        self.comboBox_uart_serial_port.addItems(self.data_serial_port)  # добавление списка
        self.comboBox_uart_serial_port.activated.connect(self.load_serial_port)

        self.pushButton_uart_connect.clicked.connect(self.pressed_UART_Connect) # обработка нажатия UART_connect
        self.pushButton_uart_test.clicked.connect(self.pressed_UART_Test)  # обработка нажатия UART_test


    def load_serial_port(self):
        ''' загрузка портов в comboBox'''
        print(self.comboBox_uart_serial_port.currentText())
        if (self.comboBox_uart_serial_port.currentText() == "Update"):
            self.data_serial_port = list(serial_ports())
            self.data_serial_port.append('Update')
            self.comboBox_uart_serial_port.clear()
            self.comboBox_uart_serial_port.addItems(self.data_serial_port)

        print(self.data_serial_port)



    def set_UART_settings(self):
        ''' считывание установленных полей и запись их в настройку порта '''
        port = self.comboBox_uart_serial_port.currentText()
        rate = self.comboBox_uart_baud_rate.currentText()
        data_bits = self.comboBox_uart_data_bits.currentText()
        parity = self.comboBox_uart_parity.currentText()
        stop_bits = self.comboBox_uart_stop_bits.currentText()

        #print (port, rate, data_bits, parity, stop_bits)

        try:
            ser.port = port
            ser.baudrate = int(rate)
            ser.bytesize = int(data_bits)

            if parity == 'none':
                ser.parity = serial.PARITY_NONE
            if parity == 'even':
                ser.parity = serial.PARITY_EVEN
            if parity == 'odd':
                ser.parity = serial.PARITY_ODD
            if parity == 'mark':
                ser.parity = serial.PARITY_MARK
            if parity == 'space':
                ser.parity = serial.PARITY_SPACE

            if stop_bits == '1':
                ser.stopbits = serial.STOPBITS_ONE
            if stop_bits == '1.5':
                ser.stopbits = serial.STOPBITS_ONE_POINT_FIVE
            if stop_bits == '2':
                ser.stopbits = serial.STOPBITS_TWO

        except IOError:
            return (1)
        return (0) # 1 - ошибка

    def pressed_UART_Connect(self):
        ''' действия происходящие при нажатии кнопки UART_Connect'''
        self.set_UART_settings()
        try:
            ser.open()
            if ser.isOpen():
                # print("serial is open!")
                self.listWidget.addItem("UART connected")
            ser.close()
        except IOError:
            ser.close()
            self.listWidget.addItem("UART disconnected")

    def pressed_UART_Test(self):
        ''' действия происходящие при нажатии кнопки UART_Test'''
        self.set_UART_settings()
        #ser.timeout = 0.1
        ser.port='COM3'
        ser.baudrate=115200
        ser.bytesize=8
        ser.parity=serial.PARITY_EVEN
        ser.stopbits=serial.STOPBITS_TWO
        ser.timeout=.1


        try:
            ser.open()
            if ser.isOpen():

                #self.listWidget.addItem("UART connected - 2")

                #ser.reset_output_buffer() # сброс буфера отправки в UART

                ser.write(bytes("1\n", 'utf-8'))
                ser.reset_input_buffer()  # сброс буфера приема из UART
                #ser.write(0x00)
                #ser.write(0x00)


                bytesToRead = ser.inWaiting() # проверка наличия данных в буфере UART приемника
                #while (bytesToRead == 0):
                    #bytesToRead = ser.inWaiting()


                # ser.write(bytes("9", 'utf-8'))
                print(ser.read(1))
            ser.close()
        except IOError:
            ser.close()
            self.listWidget.addItem("UART disconnected - 2")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Nemo = QtWidgets.QWidget()
    ui = Ui_Nemo()
    ui.setupUi(Nemo)
    Nemo.show()
    sys.exit(app.exec_())
